In [1]:
#
#  notebook to return the cell lengths
#

# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import time
import json

%matplotlib inline
import matplotlib.pyplot as plt

import os
import datetime

In [2]:
#import csv files

edu_csv = "D:\Homework\ETLProject\FBI_CS_SQL_DB\Data\Edu.csv"

edu_df = pd.read_csv(edu_csv, encoding="utf-8")
edu_df.head()

Year  Population  People over 25 with No Schooling  High School Diploma  \
0  2012  11533561.0                           63192.0            2403387.0   
1  2013  11549590.0                           65640.0            2392326.0   
2  2014  11560380.0                           66013.0            2384432.0   
3  2015  11575977.0                           68837.0            2369349.0   
4  2016  11586941.0                           68548.0            2352099.0   

        GED  Associates Degree  Bachelor's Degree  Master's Degree  \
0  291496.0           593037.0          1207216.0         504926.0   
1  295839.0           607861.0          1227819.0         521105.0   
2  297600.0           627729.0          1252463.0         537384.0   
3  299967.0           643162.0          1278763.0         554000.0   
4  302041.0           658910.0          1310995.0         571298.0   

   Professional Degree  Doctoral Degree  Name  state  No Schooling Rate  \
0             122033.0          74264.0  Ohio     39           0.547897   
1             122484.0          77052.0  Ohio     39           0.568332   
2             122786.0          81230.0  Ohio     39           0.571028   
3             124512.0          82753.0  Ohio     39           0.594654   
4             126124.0          84458.0  Ohio     39           0.591597   

   High School Education Rate  GED Rate  Associates Degree Rate  \
0                   20.838204  2.527372                5.141838   
1                   20.713515  2.561468                5.263053   
2                   20.625896  2.574310                5.430003   
3                   20.467810  2.591289                5.556006   
4                   20.299568  2.606736                5.686661   

   Bachelor's Degree Rate  Master's Degree Rate  Professional Degree Rate  \
0               10.466984              4.377885                  1.058069   
1               10.630845              4.511892                  1.060505   
2               10.834099              4.648498                  1.062128   
3               11.046696              4.785773                  1.075607   
4               11.314419              4.930533                  1.088501   

   Doctoral Degree Rate  
0              0.643895  
1              0.667141  
2              0.702659  
3              0.714868  
4              0.728907

In [4]:
edu_rounded = edu_df.round(4)
edu_rounded.head()

Year  Population  People over 25 with No Schooling  High School Diploma  \
0  2012  11533561.0                           63192.0            2403387.0   
1  2013  11549590.0                           65640.0            2392326.0   
2  2014  11560380.0                           66013.0            2384432.0   
3  2015  11575977.0                           68837.0            2369349.0   
4  2016  11586941.0                           68548.0            2352099.0   

        GED  Associates Degree  Bachelor's Degree  Master's Degree  \
0  291496.0           593037.0          1207216.0         504926.0   
1  295839.0           607861.0          1227819.0         521105.0   
2  297600.0           627729.0          1252463.0         537384.0   
3  299967.0           643162.0          1278763.0         554000.0   
4  302041.0           658910.0          1310995.0         571298.0   

   Professional Degree  Doctoral Degree  Name  state  No Schooling Rate  \
0             122033.0          74264.0  Ohio     39             0.5479   
1             122484.0          77052.0  Ohio     39             0.5683   
2             122786.0          81230.0  Ohio     39             0.5710   
3             124512.0          82753.0  Ohio     39             0.5947   
4             126124.0          84458.0  Ohio     39             0.5916   

   High School Education Rate  GED Rate  Associates Degree Rate  \
0                     20.8382    2.5274                  5.1418   
1                     20.7135    2.5615                  5.2631   
2                     20.6259    2.5743                  5.4300   
3                     20.4678    2.5913                  5.5560   
4                     20.2996    2.6067                  5.6867   

   Bachelor's Degree Rate  Master's Degree Rate  Professional Degree Rate  \
0                 10.4670                4.3779                    1.0581   
1                 10.6308                4.5119                    1.0605   
2                 10.8341                4.6485                    1.0621   
3                 11.0467                4.7858                    1.0756   
4                 11.3144                4.9305                    1.0885   

   Doctoral Degree Rate  
0                0.6439  
1                0.6671  
2                0.7027  
3                0.7149  
4                0.7289

In [9]:
# Export file as a CSV, with the Pandas index and with the header....
edu_rounded.to_csv("D:\Homework\ETLProject\FBI_CS_SQL_DB\Data\edu_rounded.csv", index=True, header=True)

In [5]:

# return the max length of characters in each column

measurer = np.vectorize(len)

res1 = measurer(edu_df.values.astype(str)).max(axis=0)
res1

array([ 4, 10,  7,  9,  8,  8,  9,  8,  8,  8, 13,  2, 18, 18, 18, 18, 18,
       18, 18, 18])

In [6]:
#import csv files

housing_csv = "D:\Homework\ETLProject\FBI_CS_SQL_DB\Data\Housing.csv"

housing_df = pd.read_csv(housing_csv, encoding="utf-8")
housing_df.head()

Year  Population  People Living in Poverty  Median Household Income  \
0  2012  11533561.0                 1723485.0                  48246.0   
1  2013  11549590.0                 1773853.0                  48308.0   
2  2014  11560380.0                 1790564.0                  48849.0   
3  2015  11575977.0                 1775836.0                  49429.0   
4  2016  11586941.0                 1732839.0                  50674.0   

   Unemployment Count  Average Cost of Rent and Utilities Combined  \
0            569218.0                                        710.0   
1            582953.0                                        718.0   
2            536573.0                                        729.0   
3            477251.0                                        730.0   
4            423956.0                                        743.0   

   Average Value of an Owner-Occupied Home  \
0                                 133700.0   
1                                 130800.0   
2                                 129600.0   
3                                 129900.0   
4                                 131900.0   

   Average Monthly Housing Expense for a Homeowner with a Mortgage  Name  \
0                                             1303.0                Ohio   
1                                             1288.0                Ohio   
2                                             1274.0                Ohio   
3                                             1246.0                Ohio   
4                                             1238.0                Ohio   

   state  Unemployment Rate  Poverty Rate  
0     39           4.935319     14.943217  
1     39           5.047391     15.358580  
2     39           4.641482     15.488799  
3     39           4.122771     15.340701  
4     39           3.658912     14.955103

In [7]:
housing_rounded = housing_df.round(4)
housing_rounded.head()

Year  Population  People Living in Poverty  Median Household Income  \
0  2012  11533561.0                 1723485.0                  48246.0   
1  2013  11549590.0                 1773853.0                  48308.0   
2  2014  11560380.0                 1790564.0                  48849.0   
3  2015  11575977.0                 1775836.0                  49429.0   
4  2016  11586941.0                 1732839.0                  50674.0   

   Unemployment Count  Average Cost of Rent and Utilities Combined  \
0            569218.0                                        710.0   
1            582953.0                                        718.0   
2            536573.0                                        729.0   
3            477251.0                                        730.0   
4            423956.0                                        743.0   

   Average Value of an Owner-Occupied Home  \
0                                 133700.0   
1                                 130800.0   
2                                 129600.0   
3                                 129900.0   
4                                 131900.0   

   Average Monthly Housing Expense for a Homeowner with a Mortgage  Name  \
0                                             1303.0                Ohio   
1                                             1288.0                Ohio   
2                                             1274.0                Ohio   
3                                             1246.0                Ohio   
4                                             1238.0                Ohio   

   state  Unemployment Rate  Poverty Rate  
0     39             4.9353       14.9432  
1     39             5.0474       15.3586  
2     39             4.6415       15.4888  
3     39             4.1228       15.3407  
4     39             3.6589       14.9551

In [10]:
# Export file as a CSV, with the Pandas index and with the header....
housing_rounded.to_csv("D:\Homework\ETLProject\FBI_CS_SQL_DB\Data\housing_rounded.csv", index=True, header=True)

In [8]:

# return the max length of characters in each column


res1 = measurer(housing_df.values.astype(str)).max(axis=0)
res1

array([ 4, 10,  9,  7,  8,  5,  8,  6, 13,  2, 18, 18])

In [26]:
#import csv files

fbi_csv = "fbi_data_final.csv"

fbi_final_df = pd.read_csv(fbi_csv, encoding="utf-8")
fbi_final_df.head()

Unnamed: 0 State  Offense_Year        Offense_Type  Offense_Count
0           0    OH          2010  aggravated_assault         4075.0
1           1    OH          2010  all_other_offenses        69074.0
2           2    OH          2010               arson          232.0
3           3    OH          2010            burglary         7022.0
4           4    OH          2010              curfew         1336.0

In [28]:

# return the max length of characters in each column


res1 = measurer(fbi_final_df.values.astype(str)).max(axis=0)
res1

array([ 4,  2,  4, 20,  8])